name: Format Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    uses: thre4dripper/Reusable-Workflows/.github/workflows/format.yml@main
    with:
      package-manager: pnpm
      format-check-command: pnpm format:check
      format-fix-command: pnpm format:fix
