name: Format Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    name: Code Formatting
    uses: thre4dripper/Reusable-Atomic-Workflows/.github/workflows/quality-format.yml@main
    with:
      package-manager: pnpm
      format-check-command: pnpm format:check
      format-fix-command: pnpm format:fix
    secrets:
      workflow-token: ${{ secrets.GITHUB_TOKEN }}
