name: Release
on:
#  push:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  unit-tests:
    name: Unit Tests
    uses: thre4dripper/Reusable-Atomic-Workflows/.github/workflows/test-unit.yml@main
    with:
      package-manager: pnpm
      test-command: pnpm test:unit
      coverage-command: pnpm run test:unit:coverage

  lint-check:
    name: Lint Check
    uses: thre4dripper/Reusable-Atomic-Workflows/.github/workflows/quality-lint.yml@main
    with:
      package-manager: pnpm
      lint-check-command: pnpm link:check

  type-check:
    name: Type Check
    uses: thre4dripper/Reusable-Atomic-Workflows/.github/workflows/quality-typecheck.yml@main
    with:
      package-manager: pnpm

  test-play-console-cli:
    name: Test Play Console CLI
    needs: [type-check, lint-check, unit-tests]
    uses: ./.github/workflows/play-console-info.yml
    secrets: inherit
